on:

  schedule:
    - cron: '*/5 * * * *'

  push:
    branches:
      - default

jobs:
  FetchForUpdateFromFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run get
        run: |
          curl --get https://pull.git.ci/process/covid19cuba/covid19cubadata.github.io
