on:
  schedule:
    - cron: '0 8-23 * * *'

  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - uses: covid19cuba/covid19cuba-action@master
        with:
          BotToken: ${{ secrets.BOT_TOKEN }}
          GroupId: ${{ secrets.GROUP_ID }}

      - name: deploy
        run: |
          git config --global user.name 'leynier'
          git config --global user.email 'leynier41@gmail.com'
          git checkout -b gh-pages
          git add .
          git commit -am "Deploy apis"
          git push -f --set-upstream origin gh-pages

      - name: ssh deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd projects/covid19cubadata.github.io
            git checkout gh-pages
            git fetch --all
            git reset --hard origin/gh-pages
